# Generated by Django 3.2.4 on 2021-10-21 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appl_mpz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpz_appl_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('part_num', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wh_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('locate', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projectgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Appl_mpz_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_value', models.CharField(max_length=20)),
                ('applID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.appl_mpz')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.welltype')),
            ],
        ),
        migrations.AddField(
            model_name='appl_mpz',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.code'),
        ),
    ]
