# Generated by Django 3.2.4 on 2021-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_well_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='comment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='req_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='trans_date',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
