# Generated by Django 3.2.4 on 2021-11-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211021_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_name', models.CharField(max_length=20)),
            ],
        ),
    ]
