# Generated by Django 3.2.4 on 2021-11-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_byers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Byers',
            new_name='Byer',
        ),
    ]
