# Generated by Django 3.2.4 on 2021-11-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_byers_byer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appl_byer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_appl_name', models.CharField(max_length=20)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.byer')),
            ],
        ),
        migrations.CreateModel(
            name='Appl_by_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_value', models.CharField(max_length=20)),
                ('applID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.appl_mpz')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.welltype')),
            ],
        ),
    ]
