# Generated by Django 3.2.4 on 2021-11-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_appl_by_data_appl_byer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appl_by_data',
            name='applID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.appl_byer'),
        ),
    ]
