# Generated by Django 3.2.4 on 2021-11-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_appl_by_data_applid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appl_by_data',
            name='byID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.byer'),
            preserve_default=False,
        ),
    ]
